language: c
install:
- sudo add-apt-repository -y ppa:directhex/monoxide
- sudo apt-get update
- sudo apt-get install --force-yes mono-devel mono-gmcs nunit-console
script:
- xbuild ./AutoCountdown.sln

